name: recipys_polars
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10.6
  - black=23.3.0
  - coverage=7.2.3
  - flake8=5.0.4
  - numpy=1.24.3
  - pandas=2.1.0
  - pytest=7.3.1
  - tqdm=4.64.1
  - scikit-learn=1.3
  - pip=23.1
  - pyarrow=12.0.1
  - pip:
    - polars==1.0.0

