name: Tests

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, "release/*", "dev"]
  schedule:
    - cron: "0 0 */14 * *" # Runs every two weeks at midnight UTC

jobs:
  run_tests_ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
      fail-fast: false

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          pip install -e ".[tests, polars, pandas]"
          pip install pytest pytest-cov --upgrade

      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run tests
        run: |
          pytest src/ tests/ -v --doctest-modules --cov=src --junitxml=junit.xml -s

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
